import Foundation

/// Centralized configuration settings for the OpenCone application.
/// Reads sensitive keys from the secure settings store for better security practices.
struct Configuration {
    // MARK: - OpenAI Configuration

    /// OpenAI API Key retrieved from secure storage.
    static var openAIAPIKey: String {
        return SecureSettingsStore.shared.getOpenAIKey()
    }
    /// The specific OpenAI model used for generating text embeddings.
    static let embeddingModel = "text-embedding-3-large"
    /// The expected dimension (size) of the vectors generated by the embedding model.
    static let embeddingDimension = 3072
    /// The specific OpenAI model used for generating completions or answers: the model catalog's
    /// default (Resources/ModelCatalog/ModelCatalog.json, shared with OpenResponses)
    static var completionModel: String { CurrentModelCatalog.defaultModel }

    // MARK: - Pinecone Configuration

    /// Pinecone API Key retrieved from secure storage.
    static var pineconeAPIKey: String {
        return SecureSettingsStore.shared.getPineconeAPIKey()
    }
    /// Pinecone Project ID retrieved from secure storage, required for authentication.
    static var pineconeProjectId: String {
        return SecureSettingsStore.shared.getPineconeProjectId()
    }
    /// Default Pinecone environment/region to use.
    static let pineconeEnvironment = "us-east-1"
    /// Control plane API version (configurable via secure store)
    static var pineconeControlPlaneVersion: String {
        let version = SecureSettingsStore.shared.getPineconeControlPlaneVersion()
        return version.isEmpty ? PineconeAPIVersions.controlPlane : version
    }
    /// Data plane API version
    static var pineconeDataPlaneVersion: String {
        let version = SecureSettingsStore.shared.getPineconeDataPlaneVersion()
        return version.isEmpty ? PineconeAPIVersions.dataPlane : version
    }
    /// Namespace management API version (preview)
    static var pineconeNamespaceVersion: String {
        let version = SecureSettingsStore.shared.getPineconeNamespaceVersion()
        return version.isEmpty ? PineconeAPIVersions.namespaces : version
    }
    /// Metadata fetch API version (preview)
    static var pineconeMetadataFetchVersion: String {
        let version = SecureSettingsStore.shared.getPineconeMetadataFetchVersion()
        return version.isEmpty ? PineconeAPIVersions.metadataFetch : version
    }

    // MARK: - Document Processing Settings

    /// Default size (in characters or tokens, depending on implementation) for text chunks.
    static let defaultChunkSize = 1024
    /// Default overlap size between consecutive text chunks to maintain context.
    static let defaultChunkOverlap = 256

    /// Maximum number of Pinecone indexes a user is allowed to create through the app.
    static let maxIndexes = 5

    /// Set of MIME types accepted for document processing, including text, documents, web, data, code, and images (for OCR).
    static let acceptedMimeTypes: Set<String> = [
        // Document formats
        "application/pdf", "text/plain",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document", // .docx
        "application/msword", // .doc

        // Web formats
        "text/html", "text/css",

        // Data formats
        "text/markdown", "application/json", "application/xml",
        "text/csv", "text/tsv", "text/rtf", "application/rtf",

        // Code formats
        "application/x-python", "text/x-python",
        "application/javascript", "text/javascript",

        // Image formats (for OCR)
        "image/png", "image/jpeg", "image/gif", "image/tiff", "image/bmp"
    ]

    /// Checks if a given MIME type is supported for processing.
    /// - Parameter mimeType: The MIME type string to check.
    /// - Returns: `true` if the MIME type is in the `acceptedMimeTypes` set, `false` otherwise.
    static func isMimeTypeSupported(_ mimeType: String) -> Bool {
        return acceptedMimeTypes.contains(mimeType)
    }

    // MARK: - Pinecone Location (Cloud/Region)

    /// Returns the preferred Pinecone cloud provider (e.g., "aws", "gcp")
    static func getPineconeCloud() -> String {
        return SecureSettingsStore.shared.getPineconeCloud()
    }

    /// Returns the preferred Pinecone region (e.g., "us-east-1")
    static func getPineconeRegion() -> String {
        return SecureSettingsStore.shared.getPineconeRegion()
    }

    // MARK: - Model Capabilities

    /// Prefixes for reasoning-capable models (gpt-6.x and gpt-5.x series, o-series)
    static let reasoningModelPrefixes: [String] = ["gpt-6", "gpt-5", "o4", "o3", "o1"]

    /// Returns true if the given model supports the Responses "reasoning" parameters
    /// This includes the gpt-6.x and gpt-5.x series, o-series models, and any later general
    /// release the model catalog recognizes by its version number
    static func isReasoningModel(_ model: String) -> Bool {
        let lowercased = model.lowercased()
        return CurrentModelCatalog.isModern(lowercased)
            || reasoningModelPrefixes.contains { lowercased.hasPrefix($0.lowercased()) }
    }
}

/// The Pinecone API versions OpenCone sends unless Settings names others, in the
/// `X-Pinecone-Api-Version` header. Pinecone's 2025 changelog (read 2026-10-01): creating a namespace
/// and fetching by metadata arrived in 2025-10. Its 2026 changelog: 2026-07 is the latest stable
/// version. The control and data planes stay on 2024-07, the version OpenCone already sends, until a
/// move to a newer one is tested against a live index.
enum PineconeAPIVersions {
    static let controlPlane = "2024-07"
    static let dataPlane = "2024-07"
    static let namespaces = "2025-10"
    static let metadataFetch = "2025-10"
    /// The latest stable version on 2026-10-01
    static let latestStable = "2026-07"
}
